services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sportlandia
      MYSQL_ROOT_PASSWORD: Root123+
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default  # Ensure db is on the default network

  app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db  # references the db container
      MYSQL_USER: root
      MYSQL_PASSWORD: Root123+
      MYSQL_DB: sportlandia
    networks:
      - default
    ports:
      - "5000:5000"

volumes:
  db-data:

networks:
  default:
